In [ ]:
#numpy basics
import numpy as np
a=np.array([1,2,3])
print(a)
print(type (a))
print(a[2])
print(a.dtype) #int32
a1=np.array({1,2,3})  
print(a1.dtype) #object
a2=np.array([1,2,3],np.float64)
print(a2.dtype) #float64
zero=np.zeros((2,5))
print(zero)
emp=np.empty((2,4))
print(emp)
ar3=np.arange(99)
print(ar3)
print(ar3.reshape(3,33))
print(ar3.flatten())
print(ar3.ravel())





In [73]:
#axis
arr=[[1,2,3],[4,0,6],[17,8,9]]
print(arr)
print(type(arr)) #python list
arr1=np.array(arr)
print(arr1)
print(type(arr1)) #numpy array
print(arr1.sum(axis=0)) 
print(arr1.sum(axis=1))
print(arr1.T) #transpose
for i in arr1.flat:
    print(i,end="")
print()
print(arr1.ndim)
print(arr1.size)
print(arr1.nbytes)
print(arr1.argmax()) #return the index where the max(17) value is present
print(arr1.argmin()) #return the index where the min(0) value is present
print(arr1.argsort()) #it will sort the elements and return index values 
print(arr1.argmax(axis=0)) 
print(arr1.argmax(axis=1)) 
print(arr1.argmin(axis=0))
print(arr1.argmin(axis=1))
print(arr1.argsort(axis=0))
print(arr1.argsort(axis=1))
print(np.where(arr1>5))
arr2=arr1.tolist()
print(type(arr2))





[[1, 2, 3], [4, 0, 6], [17, 8, 9]]
<class 'list'>
[[ 1  2  3]
 [ 4  0  6]
 [17  8  9]]
<class 'numpy.ndarray'>
[22 10 18]
[ 6 10 34]
[[ 1  4 17]
 [ 2  0  8]
 [ 3  6  9]]
1234061789
2
9
36
6
4
[[0 1 2]
 [1 0 2]
 [1 2 0]]
[2 2 2]
[2 2 0]
[0 1 0]
[0 1 1]
[[0 1 0]
 [1 0 1]
 [2 2 2]]
[[0 1 2]
 [1 0 2]
 [1 2 0]]
(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))
<class 'list'>


In [74]:
#memory space difference
import sys
py_list=[1,2,3,4]
numpy_array=np.array([1,2,3,4])
print(sys.getsizeof(1)*len(py_list))
print(numpy_array.itemsize*numpy_array.size)



112
16
